# Generated by Django 4.2.7 on 2023-11-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='translation',
            new_name='translation_text',
        ),
    ]
